name: Daily Vercel Deploy

on:
  schedule:
    - cron: '0 8 * * *' # Se ejecuta todos los días a las 8 AM UTC (ajusta según tu zona horaria)
  workflow_dispatch: # Permite ejecución manual

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
